名字: C/C++ CI

上:
 推:
 分支: [ “开发” ]
 pull_request:
 分支: [ “开发” ]

工作:
 建:

 运行: ubuntu-最新

 步骤:
    - 使用: 作/checkout@v4
    - 名字: 配置
 跑: 。/配置
    - 名字: 做
 跑: 做
    - 名字: 进行检查
 跑: 进行检查
    - 名字: 制作 distcheck
 跑: 制作 distcheck
